theme: jekyll-theme-hacker
title:Welcome to Sarang's homepage!!
 description:As github said to create your own git web pages im created this first one.Need suggestions while editing the same.If you guys have any new idea to simplify or want to fix any problem then feel free to do and merge it into master branch.
